baseURL = "https://pravilna.seveleu.com"

title = "Praviĺna!"
description = "desc"

DefaultContentLanguage = "be"
languageCode = "be-BY"

publishDir = "public"
theme="spelling"

disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
